version: '3'

env:
  DB_USERNAME: tms
  DB_PASSWORD: secret
  DB_DATABASE: tms

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install and setup application (first time)
    cmds:
      - ./bootstrap.sh

  start:
    desc: Start all containers
    cmds:
      - echo "Starting containers..."
      - docker compose up -d
      - echo "✅ Containers started!"
      - echo "📱 App{{":"}} http{{":"}}//localhost{{":"}}8080"
      - echo "📧 Mail{{":"}} http{{":"}}//localhost{{":"}}8025"

  stop:
    desc: Stop all containers
    cmds:
      - echo "Stopping containers..."
      - docker compose stop
      - echo "✅ Containers stopped!"

  restart:
    desc: Restart all containers
    deps: [stop, start]

  logs:
    desc: Show container logs (ctrl+c to exit)
    cmds:
      - docker compose logs -f

  clean:
    desc: Stop and remove all containers and volumes
    prompt: This will remove all data! Continue?
    cmds:
      - docker compose down -v
      - rm -f .app-initialized
      - echo "✅ Cleaned!"

  seed:
    desc: Import seed data (will skip if data exists)
    cmds:
      - echo "🌱 Seeding database..."
      - docker compose exec -T mysql mysql -u${DB_USERNAME} -p${DB_PASSWORD} ${DB_DATABASE} < seed.sql
      - echo "✅ Seed imported!"

  fresh:
    desc: Fresh start (rebuild containers and reseed)
    cmds:
      - echo "🔄 Fresh installation..."
      - docker compose down -v
      - rm -f .app-initialized
      - docker compose build --no-cache
      - ./bootstrap.sh

  rebuild:
    desc: Rebuild containers without removing data
    cmds:
      - echo "🔨 Rebuilding containers..."
      - docker compose down
      - docker compose build
      - docker compose up -d
      - echo "✅ Rebuild complete!"

  shell:
    desc: Open shell in app container
    cmds:
      - docker compose exec app bash

  mysql:
    desc: Open MySQL shell
    cmds:
      - docker compose exec mysql mysql -u${DB_USERNAME} -p${DB_PASSWORD} ${DB_DATABASE}

  redis:
    desc: Open Redis CLI
    cmds:
      - docker compose exec redis redis-cli

  npm:
    desc: "Run npm command (usage: task npm -- install)"
    cmds:
      - docker compose exec node npm {{.CLI_ARGS}}

  cache-clear:
    desc: Clear Laravel caches
    cmds:
      - docker compose exec app php artisan cache:clear
      - docker compose exec app php artisan config:clear
      - docker compose exec app php artisan view:clear
      - docker compose exec app php artisan route:clear
      - echo "✅ Caches cleared!"

  migrate:
    desc: Run database migrations
    cmds:
      - docker compose exec app php artisan migrate --force

  migrate-fresh:
    desc: Drop all tables and re-run migrations
    prompt: This will drop all tables! Continue?
    cmds:
      - docker compose exec app php artisan migrate:fresh --force

  migrate-fresh-seed:
    desc: Drop all tables, re-run migrations, and seed
    prompt: This will drop all tables and reseed! Continue?
    cmds:
      - docker compose exec app php artisan migrate:fresh --seed --force

  artisan:
    desc: "Run artisan command (usage: task artisan -- migrate)"
    cmds:
      - docker compose exec app php artisan {{.CLI_ARGS}}

  composer:
    desc: "Run composer command (usage: task composer -- install)"
    cmds:
      - docker compose exec app composer {{.CLI_ARGS}}

  tinker:
    desc: Open Laravel Tinker
    cmds:
      - docker compose exec app php artisan tinker

  test:
    desc: Run tests
    cmds:
      - docker compose exec app php artisan test

  ps:
    desc: Show container status
    cmds:
      - docker compose ps

  down:
    desc: Stop and remove containers
    cmds:
      - docker compose down

  up:
    desc: Start containers in foreground
    cmds:
      - docker compose up
